#+TITLE: PicaWriter -- Classes for writing Pica+ records
#+AUTHOR: David Maus
#+EMAIL: maus@hab.de

* About

PicaWriter provides classes for writing Pica+ records to PicaXML and PicaPlain.

PicaWriter is copyright (c) 2012-2015 by Herzog August Bibliothek Wolfenbüttel and released under the
terms of the GNU General Public License v3.

* Installation

You can install PicaWriter via Composer.

#+BEGIN_EXAMPLE
composer require hab/picawriter
#+END_EXAMPLE

* Usage

All writers adhere to the same simple interface: You call the =Writer::write()= function with a
record instance as argument and the function returns the record encoded in the respective output
format.

* Acknowledgements

The [[http://phix-project.org][Phix project]] makes it easy to setup and maintain a package repository for a PEAR-installable
package and integrates important tools such as [[http://phpunit.de][PHPUnit]], [[http://phing.info][Phing]], [[http://pear.php.net][PEAR]], and [[http://pirum.sensiolabs.org/][Pirum]]. Large parts of this
package would not have been possible without studying the source of [[http://search.cpan.org/dist/PICA-Record/][Pica::Record]], an open source
Perl library for handling Pica+ records by Jakob Voß, and the practical knowledge of our library's
catalogers.

* Footnotes
